plugins {
	id 'java'
	id 'org.openjfx.javafxplugin' version '0.1.0'
	id 'application'
	id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.24'
	id 'eclipse'
}

repositories {
	mavenCentral()
}

dependencies {
//	implementation 'com.google.api-client:google-api-client:2.7.0'
//	implementation 'com.google.apis:google-api-services-drive:v3-rev197-1.25.0'
//	implementation 'org.kohsuke:github-api:1.326'
//	implementation 'com.squareup.okhttp3:okhttp:4.12.0'
	

	
}

application {
	mainClassName = "koossa.plaasbestuur.Launcher"
}

javafx {
	version = "21.0.3"
	modules = [	"javafx.base", 
				"javafx.controls",
				"javafx.swing",
				"javafx.fxml",
				"javafx.graphics"]
}

gluonfx {
    target = 'host'
    if (project.hasProperty('target')) {
        target = project.getProperty('target')
    }
    appIdentifier = 'koossa.plaasbestuur'
    attachConfig {
        version = "4.0.21"
        configuration = "implementation";
        services "lifecycle", "storage", "display", "connectivity"
    }
    release {
        // Android
        appLabel = "Plaasbestuur"
        versionCode = codeNumber
        versionName = versionMajor + '.' + versionMinor + '.' + versionPatch
        providedKeyStorePath = "${System.env.GLUON_ANDROID_KEYSTOREPATH}"
        providedKeyStorePassword = "${System.env.GLUON_ANDROID_KEYSTORE_PASSWORD}"
        providedKeyAlias = "${System.env.GLUON_ANDROID_KEYALIAS}"
        providedKeyAliasPassword = "${System.env.GLUON_ANDROID_KEYALIAS_PASSWORD}"
        // iOS
        // bundleName = ""
        // bundleVersion = ""
        // bundleShortVersion = ""
        // providedSigningIdentity = ""
        // providedProvisioningProfile = ""
        // skipSigning = false
    }
}
