plugins {
	id 'java'
	id 'org.openjfx.javafxplugin' version '0.1.0'
	id 'application'
	id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.22'
	id 'eclipse'
}

repositories {
	mavenCentral()
}

dependencies {
//	implementation 'com.google.code.gson:gson:2.11.0'
}

application {
	mainClassName = "koossa.plaasbestuur.Launcher"
}

javafx {
	version = "21.0.3"
	modules = [	"javafx.base", 
				"javafx.controls",
				"javafx.swing",
				"javafx.fxml",
				"javafx.graphics"]
}

gluonfx {
    target = 'host'
    if (project.hasProperty('target')) {
        target = project.getProperty('target')
    }
}