add=Voeg by
amount=Hoeveelheid
appTitle=Plaasbestuur

buffalos=Buffels

cancel=Kanselleer
cattleTitle=Beeste
confirmDelete=Bevestig permanente verwydering van:
createNewEntry=Skep Nuwe Inskrywing

date=Datum
debugTitle=Korreksie Skerm
deleteAccount=Skrap Gebruiker
deleteEntry=Skrap Inskrywing
donkeys=Donkies

edit=Verander
endDate=Eind Datum
existingEntries=Bestaande Inskrywings
exportData=Stoor Data

filter=Filter

goats=Bokke

horses=Perde

intervals=Tydperk

language=Taal
livestock=Lewendehawe
livestockTypeAdd=Voeg lewendehawe tipe by
location=Ligging
locationDeleteConfirm=Hierdie ligging en alle gekoppelde data gaan verwyder word. Dit word aanbeveel om hierdie data op 'n ander plek te stoor, voordat hierdie aksie goedgekeur word.
locationsEdit=Wysig liggings
login=Tekin Aan

mainMenu=Hoofkieslys

newEntry=Nuwe Inskrywing

ok=OK

passmatch=** Wagwoorde moet eenders wees. **
password=Wagwoord
pigs=Varke

quit=Verlaat

rainEntryDeleteConfirm=Hierdie reënval inskrywing gaan permanent verwyder word. Wil u voortgaan hiermee?
rainfallTitle=Reënval
register=Registreer
registerTitle=Registreer Nuwe Gebruiker
remove=Verwyder
reset=Herstel

save=Stoor
saveUserCredentials=Merk om besonderhede te onthou.
seasonAverage=Seisoen Gemiddeld
seasonTotal=Seisoen Totaal
sheep=Skape
settings=Instellings
showGraph=Wys Grafiek
startDate=Begin Datum
statistics=Statestiek
switchLanguage=Verander Taal
switchView=Verander Skerm

username=Gebruikersnaam
utilities=Nutsdienste

