amount=Hoeveelheid
appTitle=Plaasbestuur

cancel=Kanselleer
cattleTitle=Beeste
createNewEntry=Skep Nuwe Inskrywing

date=Datum
debugTitle=Ontwurming Skerm
deleteAccount=Skrap Gebruiker
deleteEntry=Skrap Inskrywing

endDate=Eind Datum
existingEntries=Bestaande Inskrywings
exportData=Stoor Data

filter=Filter

language=Taal
location=Ligging
login=Tekin Aan

mainMenu=Hoofkieslys

newEntry=Nuwe Inskrywing

passmatch=** Wagwoorde moet eenders wees. **
password=Wagwoord

quit=Verlaat

rainfallTitle=Reënval
register=Registreer
registerTitle=Registreer Nuwe Gebruiker

saveUserCredentials=Merk om besonderhede te onthou.
seasonAverage=Seisoen Gemiddeld
seasonTotal=Seisoen Totaal
settings=Instellings
showGraph=Wys Grafiek
startDate=Begin Datum
statistics=Statestiek
switchLanguage=Verander Taal
switchView=Verander Skerm

username=Gebruikersnaam

