name: Android native build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: gluonhq/setup-graalvm@master
      env: 
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check env vars locations
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        unset ANDROID_SDK_ROOT
        unset ANDROID_HOME
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT

    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
          
    - name: Make staging directory
      run: mkdir stagingApk

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name:  Build
      run: ./gradlew nativeBuild -Ptarget=android

    - name:  Package
      run: ./gradlew nativePackage -Ptarget=android

    - name: Copy logs to staging
      if: always()
      run: |
        cp -r build/gluonfx/aarch64-android/gvm/log/*.log stagingApk
        cp -r build/gluonfx/log/*.log stagingApk

    - name: Copy natives to staging dir
      run: |
        cp -r build/gluonfx/aarch64-android/gvm/*.apk stagingApk

    - name: Upload
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: AndroidPackage
        path: stagingApk
